# Generated by Django 4.2.1 on 2023-05-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_remove_manga_genre_manga_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='name',
            new_name='eng_name',
        ),
        migrations.AddField(
            model_name='manga',
            name='ru_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
