# Generated by Django 4.2.1 on 2023-05-25 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('боевик', 'боевик'), ('боевые искусства', 'боевые искусства'), ('героическое фэнтези', 'героическое фэнтези'), ('детектив', 'детектив'), ('дзёсэй', 'дзёсэй'), ('драма', 'драма'), ('комедия', 'комедия'), ('научная фантастика', 'научная фантастика'), ('приключения', 'приключения'), ('романтика ', 'романтика '), ('ужасы ', 'ужасы '), ('спорт ', 'спорт ')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('manga', 'manga'), ('manhwa', 'manhva'), ('comics', 'comics')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('year', models.IntegerField()),
                ('synopsis', models.TextField(max_length=300)),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_movie.genre')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_movie.type')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=5000, verbose_name='Сообщение')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='test_movie.manga', verbose_name='манга')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
