# Generated by Django 4.2.1 on 2023-05-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_movie', '0003_rename_name_manga_eng_name_manga_ru_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='eng_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='manga',
            name='ru_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
