# Generated by Django 4.2.1 on 2023-05-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(help_text='Enter your name', max_length=30, null=True, unique=True)),
                ('email', models.EmailField(help_text='Enter your nickname', max_length=254, null=True, unique=True)),
                ('password', models.CharField(help_text='Enter your password', max_length=40, unique=True)),
                ('is_superuser', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
